### ISSUE TITLE
centos7下运行报 未找到命令

### ISSUE THREAD

**Issue by z82134359** [zhangdapao995/es-pcstat#6]
运行：./es-pcstat -collectIntervalFlag=10 -outputTypeFlag=console -sortFlat=true ./config

报错：./es-pcstat:行1: status:403: 未找到命令

是否需要安装其他额外工具以支持程序运行？

**Comment by zhangdapao745** [comment]
无需，我之前也用的centos7.6，请确认是否在curl下载的es-pcstat目录下执行的该命令？

**Comment by z82134359** [comment]
非常感谢，解决了
可能和我linux的环境有关，我刚刚重新创建了一个目录并重新下载后运行程序就正常了，但在原来那个目录运行就会报未找到命令
